// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4eGM4rcFNZsgO_6VnQr_Z8hbpfynQV3U',
    appId: '1:325746831998:web:388dd7eefc7e8eb382de2f',
    messagingSenderId: '325746831998',
    projectId: 'top-science-8fd65',
    authDomain: 'top-science-8fd65.firebaseapp.com',
    storageBucket: 'top-science-8fd65.appspot.com',
    measurementId: 'G-FDW0N3S35W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVq1hJ2eoPfk2X7jJqOJIMPX8doxaKi5g',
    appId: '1:325746831998:android:5933107a9444a55082de2f',
    messagingSenderId: '325746831998',
    projectId: 'top-science-8fd65',
    storageBucket: 'top-science-8fd65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJvfPMdFG0ksZ0VDxWw0H5H3X465L-T0',
    appId: '1:325746831998:ios:96e9446174cef32a82de2f',
    messagingSenderId: '325746831998',
    projectId: 'top-science-8fd65',
    storageBucket: 'top-science-8fd65.appspot.com',
    iosClientId: '325746831998-14eh72dor89rjj0dl75fd0l8nsg9tn35.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );
}
